/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.maiconfz.java_gradle_spring_boot_multi_module_project.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        assertEquals("Hello      World!", MessageUtils.getMessage());
    }
}
