/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.maiconfz.java_gradle_spring_boot_multi_module_project.app;

public class App {
    public static void main(String[] args) {
        System.out.println("Hello");
    }
}
