/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.maiconfz.java_gradle_spring_boot_multi_module_project.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello      World!";
    }
}
